/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as SummarizerRouteImport } from './routes/summarizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email-generator' | '/summarizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email-generator' | '/summarizer'
  id: '__root__' | '/' | '/email-generator' | '/summarizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  SummarizerRoute: typeof SummarizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  SummarizerRoute: SummarizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
