/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as ResponsibleAiRouteImport } from './routes/responsible-ai'
import { Route as SummarizerRouteImport } from './routes/summarizer'
import { Route as TaskPlannerRouteImport } from './routes/task-planner'
import { Route as WorkplaceAssistantRouteImport } from './routes/workplace-assistant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleAiRoute = ResponsibleAiRouteImport.update({
  id: '/responsible-ai',
  path: '/responsible-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskPlannerRoute = TaskPlannerRouteImport.update({
  id: '/task-planner',
  path: '/task-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkplaceAssistantRoute = WorkplaceAssistantRouteImport.update({
  id: '/workplace-assistant',
  path: '/workplace-assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/summarizer': typeof SummarizerRoute
  '/task-planner': typeof TaskPlannerRoute
  '/workplace-assistant': typeof WorkplaceAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/summarizer': typeof SummarizerRoute
  '/task-planner': typeof TaskPlannerRoute
  '/workplace-assistant': typeof WorkplaceAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/responsible-ai': typeof ResponsibleAiRoute
  '/summarizer': typeof SummarizerRoute
  '/task-planner': typeof TaskPlannerRoute
  '/workplace-assistant': typeof WorkplaceAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-generator'
    | '/responsible-ai'
    | '/summarizer'
    | '/task-planner'
    | '/workplace-assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-generator'
    | '/responsible-ai'
    | '/summarizer'
    | '/task-planner'
    | '/workplace-assistant'
  id:
    | '__root__'
    | '/'
    | '/email-generator'
    | '/responsible-ai'
    | '/summarizer'
    | '/task-planner'
    | '/workplace-assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  ResponsibleAiRoute: typeof ResponsibleAiRoute
  SummarizerRoute: typeof SummarizerRoute
  TaskPlannerRoute: typeof TaskPlannerRoute
  WorkplaceAssistantRoute: typeof WorkplaceAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ai': {
      id: '/responsible-ai'
      path: '/responsible-ai'
      fullPath: '/responsible-ai'
      preLoaderRoute: typeof ResponsibleAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-planner': {
      id: '/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof TaskPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workplace-assistant': {
      id: '/workplace-assistant'
      path: '/workplace-assistant'
      fullPath: '/workplace-assistant'
      preLoaderRoute: typeof WorkplaceAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  ResponsibleAiRoute: ResponsibleAiRoute,
  SummarizerRoute: SummarizerRoute,
  TaskPlannerRoute: TaskPlannerRoute,
  WorkplaceAssistantRoute: WorkplaceAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
